version: '2.2'
services:
  logcollector:
    image: rsyslog:latest
    container_name: logcollector
    volumes:
      - log:/log
    ports:
      - 1514:1514/tcp
      - 1514:1514/udp

volumes:
  log:
    driver: local

# networks:
#   default:
#     name: clab
#     external: true
